<a href="https://colab.research.google.com/github/barzansaeedpour/PyTorch-for-DeepLearning-Course/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introdunction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [23]:
 # scalar

 scalar = torch.tensor(7)
 scalar

tensor(7)

In [24]:
scalar.ndim

0

In [25]:
# Get tensor back as python int
scalar.item()

7

In [26]:
# Vector
vector = torch.tensor((7, 7))
vector

tensor([7, 7])

In [27]:
vector.ndim

1

In [28]:
vector.shape

torch.Size([2])

In [29]:
# MATRIX
MATRIX =  torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [30]:
MATRIX.ndim

2

In [31]:
MATRIX[0]

tensor([7, 8])

In [32]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       ])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([2, 3, 3])

In [35]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [36]:
# Create a random tensor of size(3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2400, 0.1563, 0.9221, 0.3133],
        [0.9500, 0.6187, 0.4200, 0.8976],
        [0.1129, 0.8153, 0.5845, 0.2974]])

In [37]:
random_tensor.ndim

2

In [38]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)